### ISSUE TITLE
the imgui issue

### ISSUE THREAD

**Issue by liquidzym** [moebiussurfing/ofxSurfingImGui#2]
sorry, which version imgui shoud i applied? got bunch of imgui erros 
ImGuiSliderFlags_Logarithmic 
ImDrawFlags
ScaleRatioFromValueT
etc....

**Comment by moebiussurfing** [comment]
hey @liquidzym !
what example are you trying to compile?
the ImGui ¨core¨ it´s inside this fork https://github.com/Daandelange/ofxImGui/
it`s dear imgui 1.82 docking.

**Comment by liquidzym** [comment]
i'm trying to complied with this one [2_LayoutsEngine](https://github.com/moebiussurfing/ofxSurfingImGui/tree/master/Examples/2_LayoutsEngine)
yes, i'm using the same addons ofximgui 
vs2017&of 0.11.2 really weird

**Comment by moebiussurfing** [comment]
Hey @liquidzym ,

Thanks a lot for your testing,
I am glad that someone feels that this can be useful. 👍 

----

I just made some cleaning on the **/Examples.**
Now I tested all and they are working.

I added a minimal one, good to start from: 
**Examples/00_Simple**

I am on oF GitHub patch-release branch. Not sure if it's purely 0.11.2. 
I'll try too the zip version from the oF web too.

----

I usually prepare the project with the oF **PROJECT GENERATOR**.
These are required on **addons.make:**
```
ofxImGui
ofxSurfingHelpers
ofxSurfingImGui
```

Rememeber to pick the correct **ofxImGui** fork!

----

Since two weeks ago I switched to Visual Studio 2022.
It's working very well, but do not have the addons extension. So you need to close VS and go to PG to add more ofxaddons.

But, when opening the VS project you need to check it's (alt+Enter) converted/retargeted to VS 2022 and SDK in two places.
Do it manually.
The two subfolders below the solution folder (the projectName and openframeworksLib Property Pages:

![Capture](https://user-images.githubusercontent.com/2106149/170122550-3ea2f499-fe60-49c8-9b85-08adcefd031c.PNG)

That is not required at all when using VS 2017. 
Must work there too, it's the default workflow as PG creates VS 2017 projects.

----

Tell if it works now when you test it.
Of course, don't hesitate to ask whatever about.
It's a WIP toolkit, so maybe some examples could break sometimes.

Regards!

**Comment by moebiussurfing** [comment]
PS:
Lately I noticed that the debug mode (vs release) is sometimes a little more susceptible of getting ImGui errors that crash the app. So in general, sometimes check first with the release mode. (It's seems like treating warnings as errors or trigs some internal debug stuff from ImGui notifying you that you have some "small errors" or bad practices maybe.)

PS:
The data/asses has the font file for the them. But should runs also with the data folder empty.

**Comment by moebiussurfing** [comment]
> I am on oF GitHub patch-release branch. Not sure if it's purely 0.11.2.
> I'll try too the zip version from the oF web too.

I just make the test on last oF web release version and up to date GitHub patch-release branch.
It compiled well.
I just updated the README.

## TESTED SYSTEMS

Currently Using:  
- **Windows 10** / **VS 2022** / GitHub [patch-release](https://github.com/openframeworks/openFrameworks/tree/patch-release) branch.  

Also tested legacy and working:  
- **Windows 10** / **VS 2017** / **oF ~0.10** / [oF ~0.11.2](https://github.com/openframeworks/openFrameworks/releases/download/0.11.2/of_v0.11.2_vs2017_release.zip)

**Comment by liquidzym** [comment]
ok，thank you so much for the hep, obviously i did pick up the wrong version of ofximgui addons , since i have the original one in the folder and then  i download the correct one yesterday and changed it name to another one,but in the projectGenerator still pick up the default one which i'm not awared. ok ,now everything fully  working ! 
again thank you for the help!
